"""empty message

Revision ID: 049262bcaea3
Revises: 432bad71efb8
Create Date: 2021-05-19 21:20:59.826090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049262bcaea3'
down_revision = '432bad71efb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
